spring:
 application:
  name: giga-gateway
 jpa:
  show-sql: true
 h2:
  console:
   enabled: true
   
server:
 port: 8080
 
#Eureka
eureka:
 client:
  service-url:
   defaultZone: http://localhost:9102/eureka/           
          
management:
 security:
  enabled: false
  
#route uri: mettre le nom du microservice tel que defini dans application.properties
       

  
